---
name: Gitleaks Secret Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gitleaks:
    name: Scan for Secrets with Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          scan_args: "--verbose --redact"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}